In [98]:
import pandas as pd
import openpyxl

In [99]:
df = pd.read_excel("dataset_merged.xlsx")
df.head()

,Название,Цена,URL объявления,Описание,Дата публикации,Продавец,Город,Адрес,Img,URL группы,...,dist_to_park,dist_to_bus_stop,dist_to_supermarket,Субъект РФ,Индекс города,Курортный,"Cредняя зп в городе, тыс руб (2025)",2015 население,Динамика населения за 10 лет,"ВРП района 2023, млн руб"
0,"2-к. квартира, 48,1 м², 17/17 эт.",5964400,https://www.avito.ru//kirovskaya_oblast_kirov/...,"ЖК «Скандинавия», ул. Анжелия Михеева 5.\n\nВ ...",2025-09-22 13:37:50,i198476227,Киров,"ул. Анжелия Михеева, д. 5",https://50.img.avito.st/image/1/1.8_XckLa6Xxyq...,https://www.avito.ru/kirovskaya_oblast_kirov/k...,...,0.41,0.25,0.06,Кировская область,233.0,N,69.2,493336.0,-17465.0,605915.5
1,"1-к. квартира, 39,1 м², 11/12 эт.",5829810,https://www.avito.ru//kirovskaya_oblast_kirov/...,Дом Сдан! Выберите самую лучшую квартиру для с...,2025-09-29 20:46:23,i275700606,Киров,"ул. Свободы, д. 141",https://60.img.avito.st/image/1/1.VMI9qba6-CtL...,https://www.avito.ru/kirovskaya_oblast_kirov/k...,...,0.22,0.24,0.33,Кировская область,233.0,N,69.2,493336.0,-17465.0,605915.5
2,"3-к. квартира, 52,9 м², 17/17 эт.",6400900,https://www.avito.ru//kirovskaya_oblast_kirov/...,Сохраняем традиции и создаём новые. Слобода — ...,2025-09-29 10:26:27,i198476227,Киров,"ул. Потребкооперации, д. 34, корп. 1",https://50.img.avito.st/image/1/1.8QtqMLa6XeIc...,https://www.avito.ru/kirovskaya_oblast_kirov/k...,...,1.59,0.45,0.53,Кировская область,233.0,N,69.2,493336.0,-17465.0,605915.5
3,"1-к. квартира, 39 м², 10/12 эт.",5814900,https://www.avito.ru//kirovskaya_oblast_kirov/...,Дом Сдан! Выберите самую лучшую квартиру для с...,2025-09-29 20:37:16,i275700606,Киров,"ул. Свободы, д. 141",https://00.img.avito.st/image/1/1.6FsUTra6RLJi...,https://www.avito.ru/kirovskaya_oblast_kirov/k...,...,0.22,0.24,0.33,Кировская область,233.0,N,69.2,493336.0,-17465.0,605915.5
4,"1-к. квартира, 40,1 м², 12/12 эт.",6315750,https://www.avito.ru//kirovskaya_oblast_kirov/...,Дом Сдан! Выберите самую лучшую квартиру для с...,2025-09-29 20:42:24,i275700606,Киров,"ул. Свободы, д. 141",https://00.img.avito.st/image/1/1.BinIDra6qsC-...,https://www.avito.ru/kirovskaya_oblast_kirov/k...,...,0.22,0.24,0.33,Кировская область,233.0,N,69.2,493336.0,-17465.0,605915.5

In [100]:
#Добавляем колонку с количеством комнат
df["Количество_комнат"] = df['Название'].str.split(',').str[0]
df['Количество_комнат'] = df['Количество_комнат'].str.replace('-к. квартира', '').str.strip()
df['Количество_комнат']

0        2
1        1
2        3
3        1
4        1
        ..
18817    2
18818    2
18819    1
18820    2
18821    2
Name: Количество_комнат, Length: 18822, dtype: object

In [101]:
#Добавляем колонку с площадью
df['Площадь'] = df['Название'].str.split(',').str[1]
df['Площадь'] = df['Площадь'].str.replace('м²', '').str.strip()
df['Площадь']

0        48
1        39
2        52
3        39
4        40
         ..
18817    70
18818    64
18819    41
18820    63
18821    65
Name: Площадь, Length: 18822, dtype: object

In [102]:
# Добовляем колонку с этажом
df['Этаж'] = df['Название'].str.split(',').str[2]

df['Этаж']

0              1 м²
1              1 м²
2              9 м²
3         10/12 эт.
4              1 м²
            ...
18817          6 м²
18818          2 м²
18819          3 м²
18820          4 м²
18821          6 м²
Name: Этаж, Length: 18822, dtype: object

In [103]:
#Добавление этажа и этажности дома 

import re

extracted = df['Название'].str.extract(r'(\d+)\s*/\s*(\d+)\s*эт', expand=True)

extracted.columns = ['Этаж', 'Этажность_дома']

for col in ['Этаж', 'Этажность_дома']:
    extracted[col] = pd.to_numeric(extracted[col], errors='coerce')

df[['Этаж', 'Этажность_дома']] = extracted

df[['Название', 'Этаж', 'Этажность_дома']].head()

                            Название  Этаж  Этажность_дома
0  2-к. квартира, 48,1 м², 17/17 эт.    17              17
1  1-к. квартира, 39,1 м², 11/12 эт.    11              12
2  3-к. квартира, 52,9 м², 17/17 эт.    17              17
3    1-к. квартира, 39 м², 10/12 эт.    10              12
4  1-к. квартира, 40,1 м², 12/12 эт.    12              12

In [104]:
df.head()

,Название,Цена,URL объявления,Описание,Дата публикации,Продавец,Город,Адрес,Img,URL группы,...,Индекс города,Курортный,"Cредняя зп в городе, тыс руб (2025)",2015 население,Динамика населения за 10 лет,"ВРП района 2023, млн руб",Количество_комнат,Площадь,Этаж,Этажность_дома
0,"2-к. квартира, 48,1 м², 17/17 эт.",5964400,https://www.avito.ru//kirovskaya_oblast_kirov/...,"ЖК «Скандинавия», ул. Анжелия Михеева 5.\n\nВ ...",2025-09-22 13:37:50,i198476227,Киров,"ул. Анжелия Михеева, д. 5",https://50.img.avito.st/image/1/1.8_XckLa6Xxyq...,https://www.avito.ru/kirovskaya_oblast_kirov/k...,...,233.0,N,69.2,493336.0,-17465.0,605915.5,2,48,17,17
1,"1-к. квартира, 39,1 м², 11/12 эт.",5829810,https://www.avito.ru//kirovskaya_oblast_kirov/...,Дом Сдан! Выберите самую лучшую квартиру для с...,2025-09-29 20:46:23,i275700606,Киров,"ул. Свободы, д. 141",https://60.img.avito.st/image/1/1.VMI9qba6-CtL...,https://www.avito.ru/kirovskaya_oblast_kirov/k...,...,233.0,N,69.2,493336.0,-17465.0,605915.5,1,39,11,12
2,"3-к. квартира, 52,9 м², 17/17 эт.",6400900,https://www.avito.ru//kirovskaya_oblast_kirov/...,Сохраняем традиции и создаём новые. Слобода — ...,2025-09-29 10:26:27,i198476227,Киров,"ул. Потребкооперации, д. 34, корп. 1",https://50.img.avito.st/image/1/1.8QtqMLa6XeIc...,https://www.avito.ru/kirovskaya_oblast_kirov/k...,...,233.0,N,69.2,493336.0,-17465.0,605915.5,3,52,17,17
3,"1-к. квартира, 39 м², 10/12 эт.",5814900,https://www.avito.ru//kirovskaya_oblast_kirov/...,Дом Сдан! Выберите самую лучшую квартиру для с...,2025-09-29 20:37:16,i275700606,Киров,"ул. Свободы, д. 141",https://00.img.avito.st/image/1/1.6FsUTra6RLJi...,https://www.avito.ru/kirovskaya_oblast_kirov/k...,...,233.0,N,69.2,493336.0,-17465.0,605915.5,1,39,10,12
4,"1-к. квартира, 40,1 м², 12/12 эт.",6315750,https://www.avito.ru//kirovskaya_oblast_kirov/...,Дом Сдан! Выберите самую лучшую квартиру для с...,2025-09-29 20:42:24,i275700606,Киров,"ул. Свободы, д. 141",https://00.img.avito.st/image/1/1.BinIDra6qsC-...,https://www.avito.ru/kirovskaya_oblast_kirov/k...,...,233.0,N,69.2,493336.0,-17465.0,605915.5,1,40,12,12

In [105]:
#Очистка датафрейма
df_clear = df
df_clear.drop(["Название", "URL объявления", "Описание","Продавец","Адрес","Img","URL группы","Unnamed: 10","Дата парсинга"], inplace=True, axis=1)

In [106]:
df_clear.head()

,Цена,Дата публикации,Город,is_class_eco,is_class_comfort,is_class_business,is_class_elite,is_brick,is_monolith,is_panel,...,Индекс города,Курортный,"Cредняя зп в городе, тыс руб (2025)",2015 население,Динамика населения за 10 лет,"ВРП района 2023, млн руб",Количество_комнат,Площадь,Этаж,Этажность_дома
0,5964400,2025-09-22 13:37:50,Киров,False,False,False,False,False,False,False,...,233.0,N,69.2,493336.0,-17465.0,605915.5,2,48,17,17
1,5829810,2025-09-29 20:46:23,Киров,False,False,False,False,False,False,False,...,233.0,N,69.2,493336.0,-17465.0,605915.5,1,39,11,12
2,6400900,2025-09-29 10:26:27,Киров,False,True,False,False,False,False,False,...,233.0,N,69.2,493336.0,-17465.0,605915.5,3,52,17,17
3,5814900,2025-09-29 20:37:16,Киров,False,False,False,False,False,False,False,...,233.0,N,69.2,493336.0,-17465.0,605915.5,1,39,10,12
4,6315750,2025-09-29 20:42:24,Киров,False,False,False,False,False,False,False,...,233.0,N,69.2,493336.0,-17465.0,605915.5,1,40,12,12

In [107]:
df_clear.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18822 entries, 0 to 18821
Data columns (total 52 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Цена                                 18822 non-null  int64
 1   Дата публикации                      18822 non-null  object
 2   Город                                18822 non-null  object
 3   is_class_eco                         18822 non-null  bool
 4   is_class_comfort                     18822 non-null  bool
 5   is_class_business                    18822 non-null  bool
 6   is_class_elite                       18822 non-null  bool
 7   is_brick                             18822 non-null  bool
 8   is_monolith                          18822 non-null  bool
 9   is_panel                             18822 non-null  bool
 10  is_new_build                         18822 non-null  bool
 11  has_finish_turnkey                   18822 non-null  bool
 12  has_finish_whitebox                  18822 non-null  bool
 13  has_finish_rough                     18822 non-null  bool
 14  has_playground                       18822 non-null  bool
 15  has_parking_underground              18822 non-null  bool
 16  has_parking_surface                  18822 non-null  bool
 17  has_parking_any                      18822 non-null  bool
 18  has_kindergarten                     18822 non-null  bool
 19  has_school                           18822 non-null  bool
 20  is_closed_yard                       18822 non-null  bool
 21  has_shops_nearby                     18822 non-null  bool
 22  has_fitness_nearby                   18822 non-null  bool
 23  near_metro                           18822 non-null  bool
 24  near_park                            18822 non-null  bool
 25  near_water                           18822 non-null  bool
 26  has_concierge                        18822 non-null  bool
 27  has_storage_room                     18822 non-null  bool
 28  has_panoramic_windows                18822 non-null  bool
 29  has_balcony                          18822 non-null  bool
 30  has_loggia                           18822 non-null  bool
 31  has_terrace                          18822 non-null  bool
 32  has_mortgage                         18822 non-null  bool
 33  is_assignment                        18822 non-null  bool
 34  has_discount                         18822 non-null  bool
 35  dist_to_city_center                  18822 non-null  float64
 36  dist_to_school                       18822 non-null  float64
 37  dist_to_kindergarten                 18822 non-null  float64
 38  dist_to_park                         18822 non-null  float64
 39  dist_to_bus_stop                     18822 non-null  float64
 40  dist_to_supermarket                  18822 non-null  float64
 41  Субъект РФ                           18816 non-null  object
 42  Индекс города                        18816 non-null  float64
 43  Курортный                            18816 non-null  object
 44  Cредняя зп в городе, тыс руб (2025)  18816 non-null  float64
 45  2015 население                       18566 non-null  float64
 46  Динамика населения за 10 лет         18816 non-null  float64
 47  ВРП района 2023, млн руб             18816 non-null  object
 48  Количество_комнат                    18822 non-null  object
 49  Площадь                              18822 non-null  object
 50  Этаж                                 18822 non-null  int64
 51  Этажность_дома                       18822 non-null  int64
dtypes: bool(32), float64(10), int64(3), object(7)
memory usage: 3.4+ MB

In [108]:
df_clear.describe()

,Цена,dist_to_city_center,dist_to_school,dist_to_kindergarten,dist_to_park,dist_to_bus_stop,dist_to_supermarket,Индекс города,"Cредняя зп в городе, тыс руб (2025)",2015 население,Динамика населения за 10 лет,Этаж,Этажность_дома
count,1.882200e+04,18822.000000,18822.000000,18822.000000,18822.00000,18822.000000,18822.000000,18816.000000,18816.000000,18566.000000,18816.000000,18822.000000,18822.000000
mean,7.567527e+06,53.820943,0.670411,0.601286,0.73619,0.295639,0.478944,237.913159,74.610172,271310.791124,1635.126169,6.294974,12.078259
std,1.075881e+07,441.283066,0.661669,0.610862,0.71481,0.368308,0.601701,18.778364,22.575615,121283.260897,39690.878776,4.406020,5.070355
min,8.000000e+05,0.000000,0.020000,0.020000,0.01000,0.000000,0.010000,176.000000,5.200000,29916.000000,-62664.000000,1.000000,1.000000
25%,4.908138e+06,0.000000,0.300000,0.260000,0.25000,0.100000,0.180000,228.000000,64.600000,172817.000000,-17465.000000,3.000000,9.000000
50%,6.511556e+06,2.450000,0.470000,0.450000,0.55000,0.190000,0.330000,241.000000,74.500000,275346.000000,-4756.000000,5.000000,10.000000
75%,8.834825e+06,4.250000,0.840000,0.720000,1.06000,0.350000,0.530000,250.000000,86.600000,384425.000000,6601.000000,9.000000,16.000000
max,8.974105e+08,4645.050000,9.680000,8.620000,9.06000,5.680000,8.900000,288.000000,159.300000,493336.000000,159329.000000,37.000000,45.000000

In [109]:
#Очистка от пропусков
df_clear.isnull().sum()

Цена                                     0
Дата публикации                          0
Город                                    0
is_class_eco                             0
is_class_comfort                         0
is_class_business                        0
is_class_elite                           0
is_brick                                 0
is_monolith                              0
is_panel                                 0
is_new_build                             0
has_finish_turnkey                       0
has_finish_whitebox                      0
has_finish_rough                         0
has_playground                           0
has_parking_underground                  0
has_parking_surface                      0
has_parking_any                          0
has_kindergarten                         0
has_school                               0
is_closed_yard                           0
has_shops_nearby                         0
has_fitness_nearby                       0
near_metro                               0
near_park                                0
near_water                               0
has_concierge                            0
has_storage_room                         0
has_panoramic_windows                    0
has_balcony                              0
has_loggia                               0
has_terrace                              0
has_mortgage                             0
is_assignment                            0
has_discount                             0
dist_to_city_center                      0
dist_to_school                           0
dist_to_kindergarten                     0
dist_to_park                             0
dist_to_bus_stop                         0
dist_to_supermarket                      0
Субъект РФ                               6
Индекс города                            6
Курортный                                6
Cредняя зп в городе, тыс руб (2025)      6
2015 население                         256
Динамика населения за 10 лет             6
ВРП района 2023, млн руб                 6
Количество_комнат                        0
Площадь                                  0
Этаж                                     0
Этажность_дома                           0
dtype: int64

In [110]:
#Удаление пропусков
df_clear.dropna(inplace=True)

In [111]:
df_clear.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18566 entries, 0 to 18821
Data columns (total 52 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Цена                                 18566 non-null  int64
 1   Дата публикации                      18566 non-null  object
 2   Город                                18566 non-null  object
 3   is_class_eco                         18566 non-null  bool
 4   is_class_comfort                     18566 non-null  bool
 5   is_class_business                    18566 non-null  bool
 6   is_class_elite                       18566 non-null  bool
 7   is_brick                             18566 non-null  bool
 8   is_monolith                          18566 non-null  bool
 9   is_panel                             18566 non-null  bool
 10  is_new_build                         18566 non-null  bool
 11  has_finish_turnkey                   18566 non-null  bool
 12  has_finish_whitebox                  18566 non-null  bool
 13  has_finish_rough                     18566 non-null  bool
 14  has_playground                       18566 non-null  bool
 15  has_parking_underground              18566 non-null  bool
 16  has_parking_surface                  18566 non-null  bool
 17  has_parking_any                      18566 non-null  bool
 18  has_kindergarten                     18566 non-null  bool
 19  has_school                           18566 non-null  bool
 20  is_closed_yard                       18566 non-null  bool
 21  has_shops_nearby                     18566 non-null  bool
 22  has_fitness_nearby                   18566 non-null  bool
 23  near_metro                           18566 non-null  bool
 24  near_park                            18566 non-null  bool
 25  near_water                           18566 non-null  bool
 26  has_concierge                        18566 non-null  bool
 27  has_storage_room                     18566 non-null  bool
 28  has_panoramic_windows                18566 non-null  bool
 29  has_balcony                          18566 non-null  bool
 30  has_loggia                           18566 non-null  bool
 31  has_terrace                          18566 non-null  bool
 32  has_mortgage                         18566 non-null  bool
 33  is_assignment                        18566 non-null  bool
 34  has_discount                         18566 non-null  bool
 35  dist_to_city_center                  18566 non-null  float64
 36  dist_to_school                       18566 non-null  float64
 37  dist_to_kindergarten                 18566 non-null  float64
 38  dist_to_park                         18566 non-null  float64
 39  dist_to_bus_stop                     18566 non-null  float64
 40  dist_to_supermarket                  18566 non-null  float64
 41  Субъект РФ                           18566 non-null  object
 42  Индекс города                        18566 non-null  float64
 43  Курортный                            18566 non-null  object
 44  Cредняя зп в городе, тыс руб (2025)  18566 non-null  float64
 45  2015 население                       18566 non-null  float64
 46  Динамика населения за 10 лет         18566 non-null  float64
 47  ВРП района 2023, млн руб             18566 non-null  object
 48  Количество_комнат                    18566 non-null  object
 49  Площадь                              18566 non-null  object
 50  Этаж                                 18566 non-null  int64
 51  Этажность_дома                       18566 non-null  int64
dtypes: bool(32), float64(10), int64(3), object(7)
memory usage: 3.5+ MB

In [112]:
df_clear.describe()

,Цена,dist_to_city_center,dist_to_school,dist_to_kindergarten,dist_to_park,dist_to_bus_stop,dist_to_supermarket,Индекс города,"Cредняя зп в городе, тыс руб (2025)",2015 население,Динамика населения за 10 лет,Этаж,Этажность_дома
count,1.856600e+04,18566.000000,18566.000000,18566.000000,18566.000000,18566.000000,18566.000000,18566.000000,18566.000000,18566.000000,18566.000000,18566.000000,18566.000000
mean,7.547299e+06,54.535638,0.674175,0.605376,0.737963,0.296892,0.480646,237.938921,74.536249,271310.791124,-317.567920,6.322363,12.122267
std,1.080356e+07,444.272348,0.665122,0.613871,0.715759,0.369850,0.601900,18.903056,22.718059,121283.260897,36188.145712,4.418808,5.079876
min,8.000000e+05,0.000000,0.020000,0.020000,0.010000,0.000000,0.010000,176.000000,5.200000,29916.000000,-62664.000000,1.000000,1.000000
25%,4.907000e+06,0.050000,0.300000,0.260000,0.250000,0.100000,0.170000,228.000000,64.600000,172817.000000,-17465.000000,3.000000,9.000000
50%,6.510300e+06,2.450000,0.470000,0.450000,0.550000,0.190000,0.330000,241.000000,74.500000,275346.000000,-4756.000000,5.000000,10.000000
75%,8.826735e+06,4.277500,0.850000,0.720000,1.060000,0.350000,0.530000,250.000000,86.600000,384425.000000,5571.000000,9.000000,16.000000
max,8.974105e+08,4645.050000,9.680000,8.620000,9.060000,5.680000,8.900000,288.000000,159.300000,493336.000000,159329.000000,37.000000,45.000000

In [113]:

df_clear.isnull().sum()

Цена                                   0
Дата публикации                        0
Город                                  0
is_class_eco                           0
is_class_comfort                       0
is_class_business                      0
is_class_elite                         0
is_brick                               0
is_monolith                            0
is_panel                               0
is_new_build                           0
has_finish_turnkey                     0
has_finish_whitebox                    0
has_finish_rough                       0
has_playground                         0
has_parking_underground                0
has_parking_surface                    0
has_parking_any                        0
has_kindergarten                       0
has_school                             0
is_closed_yard                         0
has_shops_nearby                       0
has_fitness_nearby                     0
near_metro                             0
near_park                              0
near_water                             0
has_concierge                          0
has_storage_room                       0
has_panoramic_windows                  0
has_balcony                            0
has_loggia                             0
has_terrace                            0
has_mortgage                           0
is_assignment                          0
has_discount                           0
dist_to_city_center                    0
dist_to_school                         0
dist_to_kindergarten                   0
dist_to_park                           0
dist_to_bus_stop                       0
dist_to_supermarket                    0
Субъект РФ                             0
Индекс города                          0
Курортный                              0
Cредняя зп в городе, тыс руб (2025)    0
2015 население                         0
Динамика населения за 10 лет           0
ВРП района 2023, млн руб               0
Количество_комнат                      0
Площадь                                0
Этаж                                   0
Этажность_дома                         0
dtype: int64

In [114]:
df_clear

,Цена,Дата публикации,Город,is_class_eco,is_class_comfort,is_class_business,is_class_elite,is_brick,is_monolith,is_panel,...,Индекс города,Курортный,"Cредняя зп в городе, тыс руб (2025)",2015 население,Динамика населения за 10 лет,"ВРП района 2023, млн руб",Количество_комнат,Площадь,Этаж,Этажность_дома
0,5964400,2025-09-22 13:37:50,Киров,False,False,False,False,False,False,False,...,233.0,N,69.2,493336.0,-17465.0,605915.5,2,48,17,17
1,5829810,2025-09-29 20:46:23,Киров,False,False,False,False,False,False,False,...,233.0,N,69.2,493336.0,-17465.0,605915.5,1,39,11,12
2,6400900,2025-09-29 10:26:27,Киров,False,True,False,False,False,False,False,...,233.0,N,69.2,493336.0,-17465.0,605915.5,3,52,17,17
3,5814900,2025-09-29 20:37:16,Киров,False,False,False,False,False,False,False,...,233.0,N,69.2,493336.0,-17465.0,605915.5,1,39,10,12
4,6315750,2025-09-29 20:42:24,Киров,False,False,False,False,False,False,False,...,233.0,N,69.2,493336.0,-17465.0,605915.5,1,40,12,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18817,7254450,2025-10-08 14:30:35,Гагарин,False,True,False,False,True,False,False,...,242.0,N,34.8,29916.0,-4865.0,556552.9,2,70,2,5
18818,6582450,2025-10-08 10:31:05,Гагарин,False,True,False,False,True,False,False,...,242.0,N,34.8,29916.0,-4865.0,556552.9,2,64,4,5
18819,4214560,2025-10-08 10:31:07,Гагарин,False,True,False,False,True,False,False,...,242.0,N,34.8,29916.0,-4865.0,556552.9,1,41,4,5
18820,6500550,2025-10-08 15:30:38,Гагарин,False,True,False,False,True,False,False,...,242.0,N,34.8,29916.0,-4865.0,556552.9,2,63,5,5
18821,6500000,2025-09-27 14:06:47,Гагарин,False,False,False,False,False,False,False,...,242.0,N,34.8,29916.0,-4865.0,556552.9,2,65,5,10

In [115]:
df_clear['Площадь'] = df_clear['Площадь'].astype(int)
df_clear['Цена'] = df_clear['Цена'].astype(int)
df_clear['Цена_за_квадратный_метр'] = df_clear['Цена'] / df_clear['Площадь']

In [116]:
df_clear.to_csv("clear_df.csv", index=False)

In [117]:
df_clear.to_excel("clear_df.xlsx", index=False)